name: deploy
on:
    workflow_dispatch:
    push:
        branches:
            - master

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - uses: actions/setup-node@v3
              with:
                  node-version: 14
            - run: yarn install
            - run: |
                  yarn export
                  mv out .out
                  find . -name ".*" | grep -w -E ".git|.out" -v | grep './' | xargs rm -rf
                  rm -rf *
                  mv .out/* ./
                  rm -rf .out
                  touch .nojekyll
                  echo 'neoburger.io' >CNAME
                  git checkout -b gh-pages
            - name: Save
              run: |
                git config --global user.email "neoburger@neoburger.io"
                git config --global user.name "neoburger"
                git add .
                git commit -m release
                git push -f --set-upstream origin gh-pages
